repos:
  - repo: local
    hooks:
      - id: strip-notebook-outputs
        name: Strip notebook outputs
        entry: jupyter nbconvert --clear-output --inplace
        language: system
        files: \.ipynb$
        types: [jupyter]
